name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.2.0,<0.3.0
  - jupyterlite-xeus-python >=1.0.0,<2.0.0
  # pyodide kernel
  - jupyterlite-pyodide-kernel==0.2.0
  # JupyterLab: dark theme
  - jupyterlab-night
