name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - jupyterlite_xeus
    - jupyterlite-javascript-kernel
    # SQLite kernel (optional)
    - jupyterlite-xeus-sqlite
    # P5 kernel (optional)
    - jupyterlite-p5-kernel
    # Lua kernel (optional)
    - jupyterlite-xeus-lua
  - jupyter_server
  - jupyterlite-core >=0.4.1,<0.5.0
  - jupyterlite-xeus>=2.0.0,<3
  # pyodide kernel
  - jupyterlite-pyodide-kernel
  # JupyterLab: dark theme
  - jupyterlab-night
