name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - matplotlib
  - sympy
  - numpy
  - pip
  - pandas
  - scikit-learn
  - python-language-server[all]
  - pip:
    - py-logic
