name: xeus-kernels
channels:
  - https://prefix.dev/emscripten-forge-4x
  - conda-forge
dependencies:
  - python=3.13

  # Python kernel
  - xeus-python
  - ipycanvas
  - matplotlib
  - pillow
  - requests
  - sympy
  - numpy
  - pip
  - pandas
  - scikit-learn
  - scipy
  - sqlalchemy
  - xeus-sqlite
  - xeus-lua
  - xeus
  - xeus-lite
  - xtl
  - nlohmann_json
  - pybind11
  - pybind11_json
  - pyjs
  - pytest
  - bzip2
  - zlib
  - sqlite
  - libffi
